---
- name: Installation Docker CE & Docker Compose
  hosts: deploy
  remote_user: ansible
  become: yes
  vars:
    docker_group: docker
    arch_mapping:
      x86_64: amd64
      aarch64: arm64

  tasks:
    - name: Installation des dépendances système
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Création du dossier keyrings (si inexistant)
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Téléchargement de la clé GPG Docker
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Ajout du dépôt Docker
      ansible.builtin.apt_repository:
        repo: >-
          deb [arch={{ arch_mapping[ansible_architecture] | default('amd64') }}
          signed-by=/etc/apt/keyrings/docker.asc]
          https://download.docker.com/linux/{{ ansible_distribution | lower }}
          {{ ansible_distribution_release }} stable
        filename: docker
        state: present

    - name: Installation des paquets Docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Démarrage et Activation du service
      ansible.builtin.service:
        name: docker
        enabled: yes
        state: started

    - name: Ajout de l'utilisateur au groupe docker
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: "{{ docker_group }}"
        append: yes